insert into product_category (name) values ('baby');
insert into product_category (name) values ('kitchen');
insert into product_category (name) values ('toiletry');

insert into product_catalog (name, price, category_id) values ('Poaceae', 53, 3);
insert into product_catalog (name, price, category_id) values ('Sapotaceae', 2, 1);
insert into product_catalog (name, price, category_id) values ('Rosaceae', 48, 2);
insert into product_catalog (name, price, category_id) values ('Brassicaceae', 12, 3);
insert into product_catalog (name, price, category_id) values ('Poaceae', 44, 2);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 67, 3);
insert into product_catalog (name, price, category_id) values ('Scrophulariaceae', 62, 3);
insert into product_catalog (name, price, category_id) values ('Boraginaceae', 87, 1);
insert into product_catalog (name, price, category_id) values ('Fagaceae', 10, 2);
insert into product_catalog (name, price, category_id) values ('Rosaceae', 4, 3);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 38, 2);
insert into product_catalog (name, price, category_id) values ('Convolvulaceae', 6, 3);
insert into product_catalog (name, price, category_id) values ('Geraniaceae', 70, 1);
insert into product_catalog (name, price, category_id) values ('Orthotrichaceae', 23, 1);
insert into product_catalog (name, price, category_id) values ('Lamiaceae', 20, 2);
insert into product_catalog (name, price, category_id) values ('Brassicaceae', 82, 1);
insert into product_catalog (name, price, category_id) values ('Iridaceae', 63, 2);
insert into product_catalog (name, price, category_id) values ('Onagraceae', 91, 2);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 13, 2);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 61, 3);
insert into product_catalog (name, price, category_id) values ('Aspleniaceae', 22, 2);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 46, 3);
insert into product_catalog (name, price, category_id) values ('Solanaceae', 19, 1);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 91, 3);
insert into product_catalog (name, price, category_id) values ('Sterculiaceae', 39, 2);
insert into product_catalog (name, price, category_id) values ('Chenopodiaceae', 56, 2);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 77, 3);
insert into product_catalog (name, price, category_id) values ('Poaceae', 95, 2);
insert into product_catalog (name, price, category_id) values ('Poaceae', 47, 2);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 18, 1);
insert into product_catalog (name, price, category_id) values ('Rosaceae', 10, 1);
insert into product_catalog (name, price, category_id) values ('Iridaceae', 48, 1);
insert into product_catalog (name, price, category_id) values ('Gentianaceae', 58, 1);
insert into product_catalog (name, price, category_id) values ('Catoscopiaceae', 57, 1);
insert into product_catalog (name, price, category_id) values ('Funariaceae', 93, 1);
insert into product_catalog (name, price, category_id) values ('Aspleniaceae', 54, 3);
insert into product_catalog (name, price, category_id) values ('Poaceae', 54, 2);
insert into product_catalog (name, price, category_id) values ('Amblystegiaceae', 18, 1);
insert into product_catalog (name, price, category_id) values ('Lamiaceae', 81, 3);
insert into product_catalog (name, price, category_id) values ('Orchidaceae', 36, 1);
insert into product_catalog (name, price, category_id) values ('Theliaceae', 84, 3);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 45, 2);
insert into product_catalog (name, price, category_id) values ('Solanaceae', 9, 2);
insert into product_catalog (name, price, category_id) values ('Salicaceae', 56, 3);
insert into product_catalog (name, price, category_id) values ('Lamiaceae', 66, 2);
insert into product_catalog (name, price, category_id) values ('Polygalaceae', 33, 2);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 10, 1);
insert into product_catalog (name, price, category_id) values ('Porpidiaceae', 43, 2);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 89, 3);
insert into product_catalog (name, price, category_id) values ('Poaceae', 9, 3);
insert into product_catalog (name, price, category_id) values ('Scrophulariaceae', 88, 2);
insert into product_catalog (name, price, category_id) values ('Rosaceae', 22, 1);
insert into product_catalog (name, price, category_id) values ('Violaceae', 100, 1);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 51, 2);
insert into product_catalog (name, price, category_id) values ('Cyperaceae', 67, 1);
insert into product_catalog (name, price, category_id) values ('Boraginaceae', 17, 1);
insert into product_catalog (name, price, category_id) values ('Dicranaceae', 54, 1);
insert into product_catalog (name, price, category_id) values ('Amaranthaceae', 51, 2);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 73, 3);
insert into product_catalog (name, price, category_id) values ('Dryopteridaceae', 43, 3);
insert into product_catalog (name, price, category_id) values ('Microcaliciaceae', 11, 3);
insert into product_catalog (name, price, category_id) values ('Piperaceae', 95, 2);
insert into product_catalog (name, price, category_id) values ('Pteridaceae', 91, 3);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 80, 1);
insert into product_catalog (name, price, category_id) values ('Berberidaceae', 23, 1);
insert into product_catalog (name, price, category_id) values ('Euphorbiaceae', 90, 3);
insert into product_catalog (name, price, category_id) values ('Ericaceae', 89, 2);
insert into product_catalog (name, price, category_id) values ('Chenopodiaceae', 58, 3);
insert into product_catalog (name, price, category_id) values ('Santalaceae', 93, 2);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 59, 3);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 12, 1);
insert into product_catalog (name, price, category_id) values ('Cyperaceae', 82, 3);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 48, 1);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 98, 2);
insert into product_catalog (name, price, category_id) values ('Parmeliaceae', 76, 1);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 48, 1);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 29, 3);
insert into product_catalog (name, price, category_id) values ('Pottiaceae', 98, 2);
insert into product_catalog (name, price, category_id) values ('Cupressaceae', 54, 3);
insert into product_catalog (name, price, category_id) values ('Bartramiaceae', 83, 2);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 20, 3);
insert into product_catalog (name, price, category_id) values ('Bignoniaceae', 35, 2);
insert into product_catalog (name, price, category_id) values ('Ranunculaceae', 80, 3);
insert into product_catalog (name, price, category_id) values ('Rosaceae', 13, 3);
insert into product_catalog (name, price, category_id) values ('Peltulaceae', 69, 3);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 60, 3);
insert into product_catalog (name, price, category_id) values ('Asteraceae', 4, 3);
insert into product_catalog (name, price, category_id) values ('Orthotrichaceae', 34, 1);
insert into product_catalog (name, price, category_id) values ('Polygalaceae', 62, 3);
insert into product_catalog (name, price, category_id) values ('Myrtaceae', 72, 1);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 16, 2);
insert into product_catalog (name, price, category_id) values ('Polemoniaceae', 82, 1);
insert into product_catalog (name, price, category_id) values ('Fabaceae', 34, 1);
insert into product_catalog (name, price, category_id) values ('Liliaceae', 81, 1);
insert into product_catalog (name, price, category_id) values ('Sapotaceae', 11, 3);
insert into product_catalog (name, price, category_id) values ('Asclepiadaceae', 45, 3);
insert into product_catalog (name, price, category_id) values ('Orchidaceae', 64, 2);
insert into product_catalog (name, price, category_id) values ('Grossulariaceae', 73, 2);
insert into product_catalog (name, price, category_id) values ('Callicostaceae', 8, 1);
insert into product_catalog (name, price, category_id) values ('Chenopodiaceae', 72, 1);

insert into product_quantity (quantity, catalog_id) values (506, 1);
insert into product_quantity (quantity, catalog_id) values (72, 2);
insert into product_quantity (quantity, catalog_id) values (937, 3);
insert into product_quantity (quantity, catalog_id) values (393, 4);
insert into product_quantity (quantity, catalog_id) values (454, 5);
insert into product_quantity (quantity, catalog_id) values (882, 6);
insert into product_quantity (quantity, catalog_id) values (337, 7);
insert into product_quantity (quantity, catalog_id) values (940, 8);
insert into product_quantity (quantity, catalog_id) values (437, 9);
insert into product_quantity (quantity, catalog_id) values (481, 10);
insert into product_quantity (quantity, catalog_id) values (769, 11);
insert into product_quantity (quantity, catalog_id) values (339, 12);
insert into product_quantity (quantity, catalog_id) values (787, 13);
insert into product_quantity (quantity, catalog_id) values (502, 14);
insert into product_quantity (quantity, catalog_id) values (436, 15);
insert into product_quantity (quantity, catalog_id) values (151, 16);
insert into product_quantity (quantity, catalog_id) values (814, 17);
insert into product_quantity (quantity, catalog_id) values (68, 18);
insert into product_quantity (quantity, catalog_id) values (874, 19);
insert into product_quantity (quantity, catalog_id) values (381, 20);
insert into product_quantity (quantity, catalog_id) values (684, 21);
insert into product_quantity (quantity, catalog_id) values (754, 22);
insert into product_quantity (quantity, catalog_id) values (933, 23);
insert into product_quantity (quantity, catalog_id) values (452, 24);
insert into product_quantity (quantity, catalog_id) values (692, 25);
insert into product_quantity (quantity, catalog_id) values (139, 26);
insert into product_quantity (quantity, catalog_id) values (989, 27);
insert into product_quantity (quantity, catalog_id) values (40, 28);
insert into product_quantity (quantity, catalog_id) values (292, 29);
insert into product_quantity (quantity, catalog_id) values (132, 30);
insert into product_quantity (quantity, catalog_id) values (660, 31);
insert into product_quantity (quantity, catalog_id) values (17, 32);
insert into product_quantity (quantity, catalog_id) values (286, 33);
insert into product_quantity (quantity, catalog_id) values (945, 34);
insert into product_quantity (quantity, catalog_id) values (2, 35);
insert into product_quantity (quantity, catalog_id) values (274, 36);
insert into product_quantity (quantity, catalog_id) values (37, 37);
insert into product_quantity (quantity, catalog_id) values (65, 38);
insert into product_quantity (quantity, catalog_id) values (225, 39);
insert into product_quantity (quantity, catalog_id) values (27, 40);
insert into product_quantity (quantity, catalog_id) values (908, 41);
insert into product_quantity (quantity, catalog_id) values (152, 42);
insert into product_quantity (quantity, catalog_id) values (966, 43);
insert into product_quantity (quantity, catalog_id) values (593, 44);
insert into product_quantity (quantity, catalog_id) values (136, 45);
insert into product_quantity (quantity, catalog_id) values (557, 46);
insert into product_quantity (quantity, catalog_id) values (736, 47);
insert into product_quantity (quantity, catalog_id) values (182, 48);
insert into product_quantity (quantity, catalog_id) values (565, 49);
insert into product_quantity (quantity, catalog_id) values (575, 50);
insert into product_quantity (quantity, catalog_id) values (15, 51);
insert into product_quantity (quantity, catalog_id) values (187, 52);
insert into product_quantity (quantity, catalog_id) values (845, 53);
insert into product_quantity (quantity, catalog_id) values (488, 54);
insert into product_quantity (quantity, catalog_id) values (437, 55);
insert into product_quantity (quantity, catalog_id) values (878, 56);
insert into product_quantity (quantity, catalog_id) values (588, 57);
insert into product_quantity (quantity, catalog_id) values (178, 58);
insert into product_quantity (quantity, catalog_id) values (371, 59);
insert into product_quantity (quantity, catalog_id) values (895, 60);
insert into product_quantity (quantity, catalog_id) values (142, 61);
insert into product_quantity (quantity, catalog_id) values (583, 62);
insert into product_quantity (quantity, catalog_id) values (508, 63);
insert into product_quantity (quantity, catalog_id) values (38, 64);
insert into product_quantity (quantity, catalog_id) values (740, 65);
insert into product_quantity (quantity, catalog_id) values (261, 66);
insert into product_quantity (quantity, catalog_id) values (416, 67);
insert into product_quantity (quantity, catalog_id) values (762, 68);
insert into product_quantity (quantity, catalog_id) values (886, 69);
insert into product_quantity (quantity, catalog_id) values (953, 70);
insert into product_quantity (quantity, catalog_id) values (93, 71);
insert into product_quantity (quantity, catalog_id) values (772, 72);
insert into product_quantity (quantity, catalog_id) values (909, 73);
insert into product_quantity (quantity, catalog_id) values (65, 74);
insert into product_quantity (quantity, catalog_id) values (228, 75);
insert into product_quantity (quantity, catalog_id) values (217, 76);
insert into product_quantity (quantity, catalog_id) values (212, 77);
insert into product_quantity (quantity, catalog_id) values (143, 78);
insert into product_quantity (quantity, catalog_id) values (72, 79);
insert into product_quantity (quantity, catalog_id) values (784, 80);
insert into product_quantity (quantity, catalog_id) values (667, 81);
insert into product_quantity (quantity, catalog_id) values (931, 82);
insert into product_quantity (quantity, catalog_id) values (316, 82);
insert into product_quantity (quantity, catalog_id) values (800, 84);
insert into product_quantity (quantity, catalog_id) values (135, 85);
insert into product_quantity (quantity, catalog_id) values (438, 86);
insert into product_quantity (quantity, catalog_id) values (517, 87);
insert into product_quantity (quantity, catalog_id) values (476, 88);
insert into product_quantity (quantity, catalog_id) values (637, 89);
insert into product_quantity (quantity, catalog_id) values (334, 90);
insert into product_quantity (quantity, catalog_id) values (694, 91);
insert into product_quantity (quantity, catalog_id) values (92, 92);
insert into product_quantity (quantity, catalog_id) values (242, 93);
insert into product_quantity (quantity, catalog_id) values (402, 94);
insert into product_quantity (quantity, catalog_id) values (440, 95);
insert into product_quantity (quantity, catalog_id) values (759, 96);
insert into product_quantity (quantity, catalog_id) values (295, 97);
insert into product_quantity (quantity, catalog_id) values (143, 98);
insert into product_quantity (quantity, catalog_id) values (514, 99);
insert into product_quantity (quantity, catalog_id) values (97, 100);

